stages:          # List of stages for jobs, and their order of execution
  - sync

sync-tags:       # This job runs in the build stage, which runs first.
  stage: sync
  script:
    - echo "Running"
    - ls -alh
    - git remote add cloud "https://$REMOTE_REPO_USERNAME:$REMOTE_REPO_PASSWORD@$REMOTE_REPO_URL"
    - git remote -v
    - git ls-remote --tags cloud

