stages:          # List of stages for jobs, and their order of execution
  - sync

sync-tags:       # This job runs in the build stage, which runs first.
  stage: sync
  script:
    - echo "Running"
    - ls -alh
    - git config credential.$REMOTE_REPO_URL '!f() {echo "username=${REMOTE_REPO_USERNAME}"; echo "password=${REMOTE_REPO_PASSWORD}"; }; f'
    - git remote add cloud $REMOTE_REPO_URL
    - git ls-remote --tags cloud

