stages:          # List of stages for jobs, and their order of execution
  - sync

sync-tags:       # This job runs in the build stage, which runs first.
  stage: sync
  script:
    - echo "Running"
    - ls -alh
    - git remote remove cloud
    - git remote add cloud "https://$CLOUD_REPO_USERNAME:$CLOUD_REPO_PASSWORD@$CLOUD_REPO_URL"
    - needle=https://
    - ORIGIN_REPO_URL="${CI_PROJECT_URL/"$needle"/""}" # replace the https from the project url
    - git remote remove origin
    - git remote add origin "https://$ORIGIN_REPO_USERNAME:$ORIGIN_REPO_PASSWORD@$ORIGIN_REPO_URL"
    - git remote -v
    - git ls-remote --tags cloud
    - git ls-remote --tags origin
